# Generated by Django 3.2.9 on 2022-04-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20220410_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
    ]
